In [2]:
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

In [5]:
vaccination = pd.read_csv('/content/drive/MyDrive/Education/ST.CLAIR_COLLEGE/Project_datasets/vaccinations.csv')

In [7]:
vaccination.head()

,date,location_key,new_persons_vaccinated,cumulative_persons_vaccinated,new_persons_fully_vaccinated,cumulative_persons_fully_vaccinated,new_vaccine_doses_administered,cumulative_vaccine_doses_administered,new_persons_vaccinated_pfizer,cumulative_persons_vaccinated_pfizer,...,new_persons_fully_vaccinated_janssen,cumulative_persons_fully_vaccinated_janssen,new_vaccine_doses_administered_janssen,cumulative_vaccine_doses_administered_janssen,new_persons_vaccinated_sinovac,total_persons_vaccinated_sinovac,new_persons_fully_vaccinated_sinovac,total_persons_fully_vaccinated_sinovac,new_vaccine_doses_administered_sinovac,total_vaccine_doses_administered_sinovac
0,25-01-2021,AD,NaN,576.0,NaN,NaN,NaN,576.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01-02-2021,AD,460.0,1036.0,NaN,NaN,460.0,1036.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10-02-2021,AD,255.0,1291.0,NaN,NaN,255.0,1291.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,12-02-2021,AD,331.0,1622.0,NaN,NaN,331.0,1622.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19-02-2021,AD,519.0,2141.0,NaN,NaN,519.0,2141.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
GDP = pd.read_csv('/content/drive/MyDrive/Education/ST.CLAIR_COLLEGE/Project_datasets/world-gdp-gross-domestic-product.csv')

In [10]:
GDP.head()

         date   GDP ( Billions of US $)   Per Capita (US $)   Annual % Change
0  1960-12-31               1392.276589            459.2600               NaN
1  1961-12-31               1448.625355            471.4794            3.7900
2  1962-12-31               1550.548210            495.8684            5.3160
3  1963-12-31               1671.614362            523.4413            5.1854
4  1964-12-31               1830.292049            561.3501            6.5583